services:
  web:
    image: node:14
    container_name: noble_app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8081:8080"
    command: npm start
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"