version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://noblestride:szcNy266OSYed9vMLf2DGwHsYSiE8qpg@dpg-ctucl01u0jms73f5qtfg-a/noblestride_be28
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: noblestride_be28
      POSTGRES_USER: noblestride
      POSTGRES_PASSWORD: szcNy266OSYed9vMLf2DGwHsYSiE8qpg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: