services:
  userservice-db:
    image: postgres:16.3
    container_name: noblestride-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - userservice-db-data:/var/lib/postgresql/data
    networks:
      - noblestride-network

  app:
    image: noblestride:1.0
    container_name: noblestride
    restart: on-failure
    depends_on:
      userservice-db:
        condition: service_healthy

    networks:
      - noblestride-network
    ports:
      - "3001:3001"
    env_file:
      - .env

volumes:
  userservice-db-data:

networks:
  noblestride-network:
    driver: bridge
